import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const distStyles = resolve(root, 'dist/styles')

if (!existsSync(distStyles)) {
  mkdirSync(distStyles, { recursive: true })
}

const tokenFiles = [
  'colors.css',
  'typography.css',
  'spacing.css',
  'sizing.css',
  'radius.css',
  'motion.css',
  'z-index.css',
  'breakpoints.css',
]

const banner = (name) =>
  `/* @dskripchenko/ui — ${name}. Auto-generated by scripts/build-styles.mjs. Do not edit. */\n`

const read = (rel) => readFileSync(resolve(root, rel), 'utf8').trim()

const write = (name, body) => {
  const out = resolve(distStyles, name)
  writeFileSync(out, banner(name) + body + '\n', 'utf8')
  process.stdout.write(`  ${name} (${body.length} bytes)\n`)
}

process.stdout.write('build-styles: emitting dist/styles/*\n')

const tokens = tokenFiles.map((f) => read(`src/tokens/${f}`)).join('\n\n')
write('tokens.css', tokens)

const themes = read('src/styles/themes.css')
write('themes.css', themes)

const reset = read('src/styles/reset.css')
write('reset.css', reset)

const global = read('src/styles/global.css')
write('global.css', global)

const indexCssPath = resolve(distStyles, 'index.css')
const components = existsSync(indexCssPath) ? readFileSync(indexCssPath, 'utf8').trim() : ''
if (!components) {
  process.stderr.write(
    'build-styles: WARN dist/styles/index.css missing — did vite build run first?\n',
  )
}
const all = [tokens, themes, reset, global, components].filter(Boolean).join('\n\n')
write('all.css', all)

process.stdout.write('build-styles: done\n')
